name: lumos
description: "Easily integrate powerful image editing capabilities into your Flutter applications with Lumos."
version: 0.0.5
homepage: https://github.com/ArmanKhanTech/Lumos

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.2
  colorfilter_generator: ^0.0.8
  extended_image: ^9.0.7
  image: ^4.0.17
  image_editor: ^1.3.0
  screenshot: ^3.0.0
  image_pixels: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
