name: pixel
description: "A Flutter image editor package."
version: 0.0.1
homepage: https://https://github.com/ArmanKhanTech/Pixel

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  blurrycontainer: ^2.1.0
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.2
  colorfilter_generator: ^0.0.8
  extended_image: ^8.1.1
  image: ^4.0.17
  image_editor: ^1.3.0
  screenshot: ^3.0.0
  image_pixels: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: